Added exporter details to README
ibm-observability/instanaexporter pull request #3
Opened 2022-08-15 09:24 UTC by willianpc

This PR adds detailed info about the Instana Exporter, as well as to how to setup its parameters.

2022-08-15 14:14 UTC, hickeyma reviewed
@willianpc Thank you for pushing the README. The content looks good. Some feedback inline.

2022-08-15 14:14 UTC, hickeyma commented on README.md
> +However, customers who wish to adopt the OpenTelemetry Collector can replace the Instana Agent by their custom OpenTelemetry Collector, by including the Instana Exporter into the build.
I understand what you are doing here to show the value of the agent but I think from a community standpoint, it would be better to simplify this overview paragraph.

Here is my suggestion:

"The Instana exporter converts OpenTelemetry log, metric and trace data to <Instana Content> and then sends to the Instana Backend."

It would be great if you could add links to the content and backend.

2022-08-15 14:14 UTC, hickeyma commented on README.md
> +      exporters: [logging]
We should add the exporter to metrics and also add logging as well.

2022-08-17 11:16 UTC, hickeyma requested changes

2022-08-17 11:16 UTC, hickeyma commented on README.md
> + * ``agent_endpoint``: The Instana backend endpoint that the Exporter connects to. It depends on your region and it starts with ``https://serverless-``. It corresponds to the Instana environment vari
Should this be just `endpoint`?

2022-08-18 07:39 UTC, willianpc commented on README.md
> +      exporters: [logging]
I believe that we agreed that logging and metrics won't be included at this point, after further discussions, is that correct?

2022-08-18 07:57 UTC, willianpc commented on README.md
> + * ``agent_endpoint``: The Instana backend endpoint that the Exporter connects to. It depends on your region and it starts with ``https://serverless-``. It corresponds to the Instana environment vari
If you are talking about the ``agent_endpoint`` parameter, I think this is up to you, no?
This is part of the exporter config, as far as I know. 

If you are asking my opinion, I would say that it makes sense to omit the "agent" part, so that the exporter looks more decoupled from the Instana Agent, as this seems to be a good thing, as you mentioned [above](https://github.com/ibm-observability/instanaexporter/pull/3#discussion_r945784561).

2022-08-18 09:01 UTC, hickeyma commented on README.md
> +      exporters: [logging]
That is correct. @hughluo said it was ok as the Instana backend doesn't support them yet.

2022-08-18 09:02 UTC, hickeyma commented on README.md
> + * ``agent_endpoint``: The Instana backend endpoint that the Exporter connects to. It depends on your region and it starts with ``https://serverless-``. It corresponds to the Instana environment vari
ok, remove the `agent_` prefix then

2022-08-18 12:02 UTC, hickeyma requested changes
Nearly there @willianpc. Just 2 small things.

2022-08-18 12:02 UTC, hickeyma commented on README.md
> +The Instana Exporter converts OpenTelemetry trace data and then sends to the [Instana Backend](https://www.ibm.com/docs/en/instana-observability/current?topic=setting-up-managing-instana).
trace data and then sends to --> trace data and then sends it to

2022-08-18 12:02 UTC, hickeyma commented on README.md
> +| zone           | The zone to place this monitored component into. It corresponds to the Instana environment variable ``INSTANA_ZONE`` |
`zone` entry should be removed

2022-08-18 12:57 UTC, hickeyma approved these changes
LGTM, thanks @willianpc for effort on this.

2022-08-18 12:57 UTC, merged